#!/bin/sh

# Build top.v into a bitstream, using either Vivado or yosys+nextpnr-xilinx.
# Copied mostly from ../mk

odir=build-ebaz
rm -rf $odir
mkdir -p $odir
../mkpll >$odir/pll.v
../../fpgasynth -sv -x -o $odir/ebaz -t top -L ../.. "$@" $odir/pll.v \
    audio_clock_regeneration_packet.sv audio_info_frame.sv \
    audio_sample_packet.sv auxiliary_video_information_info_frame.sv \
    hdmi.sv packet_assembler.sv packet_picker.sv \
    source_product_description_info_frame.sv tmds_channel.sv \
    top.v
