#!/bin/sh

# Build ebaz.v into a bitstream, using either Vivado or yosys+nextpnr-xilinx.
# Default is Vivado; use -y for yosys+nextpnr-xilinx.
# Currently, HDMI only produces a bitstream in Vivado.  Back when I supported
# f4pga, it produced a bitstream as well, but that bitstream was crap compared
# to the Vivado output (corrupted video and only 2 modes w/ non-audio, and
# even more corrupted video and no audio w/ audio).  In fact, other than
# retaining compatibility with yosys in case MMCM and DDR out are supported
# correctly, I can't see any reason to use the free tools.

odir=build-ebaz
rm -rf $odir
# Vivado seems to eventually create this itself, but not before complaining
mkdir -p $odir
# So I might as well create pll.v there
./mkpll >$odir/pll.v
#ULX_DIR=../../ulx3s-misc/examples
#LCD_DIR=${ULX_DIR}/spi_display/hdl/spi_display_verilog
#DVI_DIR=${ULX_DIR}/dvi/hdl
LCD_DIR=ulx3s-misc
DVI_DIR=ulx3s-misc
#UART_DIR=$HOME/fpga/j1c/verilog
UART_DIR=j1c
#LIB_DIR=${HOME}/fpga/lib
LIB_DIR=..

# uart.v and ebaz.v at bottom to avoid `default_nettype none affecting others
# FIXME: make nextpnr-xilinx at least produce a bitstream, even if broken
# Currently fails w/ ODDR->IOBUFDS:
# ERROR: Failed to route arc 0 of net 'genblk1[2].ddr_out', from SITEWIRE/OLOGIC_X0Y96/OUTFF_Q to SITEWIRE/IOB_X0Y95/O_IN.
fpgasynth -L${LIB_DIR} -sv -x -o $odir/ebaz -t top "$@" $odir/pll.v \
    ${LCD_DIR}/lcd_video.v \
    ${DVI_DIR}/vga.v \
    hdmi/audio_clock_regeneration_packet.sv hdmi/audio_info_frame.sv \
    hdmi/audio_sample_packet.sv hdmi/auxiliary_video_information_info_frame.sv \
    hdmi/hdmi.sv hdmi/packet_assembler.sv hdmi/packet_picker.sv \
    hdmi/source_product_description_info_frame.sv hdmi/tmds_channel.sv \
    ${UART_DIR}/uart.v \
    ebaz.v
